<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Sgpla.BuildingBlocks.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sgpla.SharedKernel\Sgpla.SharedKernel.csproj" />
  </ItemGroup>

</Project>
