/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteImport } from './routes/_panel'
import { Route as ComponentesRouteImport } from './routes/componentes'
import { Route as PanelIndexRouteImport } from './routes/_panel/index'
import { Route as PanelUsuariosRouteImport } from './routes/_panel/usuarios'

const PanelRoute = PanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentesRoute = ComponentesRouteImport.update({
  id: '/componentes',
  path: '/componentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelUsuariosRoute = PanelUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => PanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PanelIndexRoute
  '/componentes': typeof ComponentesRoute
  '/usuarios': typeof PanelUsuariosRoute
}
export interface FileRoutesByTo {
  '/componentes': typeof ComponentesRoute
  '/usuarios': typeof PanelUsuariosRoute
  '/': typeof PanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_panel': typeof PanelRouteWithChildren
  '/componentes': typeof ComponentesRoute
  '/_panel/usuarios': typeof PanelUsuariosRoute
  '/_panel/': typeof PanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/componentes' | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to: '/componentes' | '/usuarios' | '/'
  id: '__root__' | '/_panel' | '/componentes' | '/_panel/usuarios' | '/_panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PanelRoute: typeof PanelRouteWithChildren
  ComponentesRoute: typeof ComponentesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/componentes': {
      id: '/componentes'
      path: '/componentes'
      fullPath: '/componentes'
      preLoaderRoute: typeof ComponentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/': {
      id: '/_panel/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/usuarios': {
      id: '/_panel/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof PanelUsuariosRouteImport
      parentRoute: typeof PanelRoute
    }
  }
}

interface PanelRouteChildren {
  PanelUsuariosRoute: typeof PanelUsuariosRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelUsuariosRoute: PanelUsuariosRoute,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PanelRoute: PanelRouteWithChildren,
  ComponentesRoute: ComponentesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
