<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Sgpla.Modules.Publicacion</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Sgpla.SharedKernel\Sgpla.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Sgpla.BuildingBlocks.Infrastructure\Sgpla.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>

  <!-- Dependencias entre módulos -->
  <ItemGroup>
    <ProjectReference Include="..\..\Institucional\Sgpla.Modules.Institucional\Sgpla.Modules.Institucional.csproj" />
    <ProjectReference Include="..\..\OfertaEducativa\Sgpla.Modules.OfertaEducativa\Sgpla.Modules.OfertaEducativa.csproj" />
    <ProjectReference Include="..\..\Catalogos\Sgpla.Modules.Catalogos\Sgpla.Modules.Catalogos.csproj" />
  </ItemGroup>

</Project>
