<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Sgpla.Database</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dbup-sqlserver" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Baseline\baseline.sql" />
    <EmbeddedResource Include="Scripts\**\*.sql" />
  </ItemGroup>

</Project>
