<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Sgpla.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\Sgpla.SharedKernel\Sgpla.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Sgpla.BuildingBlocks.Application\Sgpla.BuildingBlocks.Application.csproj" />
  </ItemGroup>

</Project>
