<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Sgpla.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\Sgpla.SharedKernel\Sgpla.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Sgpla.BuildingBlocks.Application\Sgpla.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Sgpla.BuildingBlocks.Infrastructure\Sgpla.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalogos\Sgpla.Modules.Catalogos\Sgpla.Modules.Catalogos.csproj" />
    <ProjectReference Include="..\..\src\Modules\Institucional\Sgpla.Modules.Institucional\Sgpla.Modules.Institucional.csproj" />
  </ItemGroup>

</Project>
