<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Sgpla.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="ClosedXML" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sgpla.Api\Sgpla.Api.csproj" />
    <ProjectReference Include="..\..\src\Sgpla.Database\Sgpla.Database.csproj" />
  </ItemGroup>

</Project>
