namespace Sgpla.IntegrationTests.OfertaEducativa;

/// <summary>
/// Plan de estudios de ejemplo de la UV (Ingeniería de Software, plan 2014): las 58 experiencias educativas del Excel,
/// listas para el cuerpo de la importación. Los datos se extrajeron una sola vez del archivo, con los perfiles completos;
/// las pruebas no leen el <c>.xlsx</c>. Las claves de área son los ids de la semilla (<c>111</c> a 1, <c>112</c> a 2 y
/// <c>113</c> a 3); una celda de horas vacía es 0 y un perfil vacío es <c>null</c>.
/// </summary>
internal static class PlanEjemploIsof14
{
    public const string Codigo = "ISOF-14-E-CR";

    public static IReadOnlyList<ExperienciaDeEjemplo> ExperienciasEducativas { get; } =
    [
        new("ENSO", "38003", "HABILIDADES DE COMUNICACION  ", 2, 2, 6, 1, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software, área de la Computación o área administrativa; experiencia docente en el nivel superior y preferentemente, con cursos de formación y experiencia laboral en el área de comunicación y/o desarrollo de software."),
        new("FBGR", "80001", "COMPUTACION BASICA  ", 0, 6, 6, 1, "Lic.en informática, sistemas computacionales administrativos, sistemas computacionales, informática administrativa, ing. en sistemas computacionales o en administración de sistemas; o bien grado de licenciatura en cualquier área de conocimiento con resultado satisfactorio en el proceso de demostración de competencias de las habilidades de cómputo aplicado por la academia estatal de la EE, o haber acreditado el Diplomado en Metodología del aprendizaje distribuido aplicado a la computación básica."),
        new("FBGR", "80002", "HABILIDADES DEL PENSAMIENTO CRITICO Y CREATIVO ", 2, 2, 6, 1, "Licenciatura en cualquiera de las áreas del conocimiento, preferentemente con estudios de posgrado, y haber acreditado el proceso de actualización del enfoque de pensamiento crítico para la solución de problemas, avalado por el Área de Formación Básica General de la Universidad Veracruzana."),
        new("FBGR", "80003", "INGLES I  ", 0, 6, 6, 1, "Licenciatura en lengua inglesa; o licenciatura en cualquier área del conocimiento con Especialización en Enseñanza del inglés y/o Maestría en la Enseñanza del Inglés."),
        new("FBGR", "80004", "INGLES II  ", 0, 6, 6, 1, "Licenciatura en lengua inglesa; o licenciatura en cualquier área del conocimiento con Especialización en Enseñanza del inglés y/o Maestría en la Enseñanza del Inglés."),
        new("FBGR", "80005", "LECTURA Y REDACCION A TRAVES DEL ANALISIS DEL MUNDO CONTEMPORANEO ", 2, 2, 6, 1, "Lic. en el área de Lengua y Literatura, Lingüística o Comunicación; o bien, grado de licenciatura en cualquier área de conocimiento con resultado satisfactorio en el proceso de demostración de competencias de la lengua española aplicado por la Academia Estatal de Lectura y Redacción, o haber acreditado el Diplomado en Competencias de la Lengua Española para el MEIF."),
        new("FBGT", "80001", "COMPUTACION BASICA  ", 0, 6, 6, 1, null),
        new("FBGT", "80002", "HABILIDADES DEL PENSAMIENTO CRITICO Y CREATIVO ", 2, 2, 6, 1, null),
        new("FBGT", "80003", "INGLES I  ", 0, 6, 6, 1, null),
        new("FBGT", "80004", "INGLES II  ", 0, 6, 6, 1, null),
        new("FBGT", "80005", "LECTURA Y REDACCION A TRAVES DEL ANALISIS DEL MUNDO CONTEMPORANEO ", 2, 2, 6, 1, null),
        new("MASF", "38004", "LABORATORIO DE RESOLUCION DE PROBLEMAS  ", 1, 3, 5, 1, "Licenciado en Ingeniería de Software, en Informática o afín,  con posgrado en Ingeniería de Software o en el área de la Computación; preferentemente con cursos de formación docente y con experiencia profesional en el área de  desarrollo de software de al menos un año."),
        new("MATS", "38001", "FUNDAMENTOS DE MATEMATICAS  ", 3, 2, 8, 1, "Licenciado en física, matemáticas, actuaría, estadística o ingeniería, con grado de maestría y/o doctorado, con cursos de formación pedagógica, con experiencia docente."),
        new("MATS", "38002", "ALGEBRA LINEAL PARA COMPUTACION  ", 2, 3, 7, 1, "Licenciado en matemáticas, actuaría, estadística o ingeniería, con grado de maestría y/o doctorado, con cursos de formación pedagógica, con experiencia docente.\n\n"),
        new("MATS", "38003", "PROBABILIDAD Y ESTADISTICA PARA COMPUTACION  ", 3, 2, 8, 1, "Licenciado en matemáticas, actuaría, estadística o ingeniería, con grado de maestría y/o doctorado, con cursos de formación pedagógica, con experiencia docente."),
        new("MATS", "38005", "MATEMATICAS DISCRETAS  ", 3, 2, 8, 1, "Licenciado en Informática o carrera afín, Matemáticas o Estadística, con grado de Maestría y/o Doctorado, con cursos de formación pedagógica, con experiencia docente."),
        new("PRGM", "38001", "INTRODUCCION A LA PROGRAMACION  ", 2, 4, 8, 1, "Lic. En Informática o carrera afín, con posgrado en el área de la computación, con experiencia en programación orientada a objetos y/o certificación en lenguajes de programación orientada a objetos, experiencia docente a nivel superior en el área de programación y cursos de formación docente."),
        new("PRGM", "38002", "PROGRAMACION  ", 3, 3, 9, 1, "Licenciado en Informática o carrera afín, con posgrado en el área de la computación, con experiencia en programación orientada a objetos y/o certificación en lenguajes de programación orientada a objetos, experiencia docente a nivel superior en el área de programación y cursos de formación docente."),
        new("APSO", "38001", "PROCESOS PARA LA INGENIERIA DE SOFTWARE  ", 4, 2, 10, 2, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, con cursos de formación docente y experiencia docente a nivel superior, con experiencia profesional en el área de desarrollo de software de al menos dos años."),
        new("APSO", "38003", "ADMINISTRACION DE PROYECTOS DE SOFTWARE  ", 4, 2, 10, 2, "Licenciado en Ingeniería de Software, en Informática o afín,  con posgrado en Ingeniería de Software o en el área de la Computación; con cursos de formación docente y experiencia docente en el nivel superior, con experiencia profesional en el área de administración de proyectos de software de al menos dos años."),
        new("ARSI", "38008", "SISTEMAS OPERATIVOS  ", 3, 3, 9, 2, "Lic. en Informática o afín con certificación en administración de sistemas operativos o maestría en Ciencias de la Computación o afín, con experiencia en la administración de sistemas operativos Windows y Unix, experiencia docente a nivel superior y cursos de formación pedagógica."),
        new("CSOF", "38001", "PRUEBA DE SOFTWARE  ", 4, 2, 10, 2, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, con experiencia docente a nivel superior, con experiencia profesional en el área de desarrollo de software de al menos un año, preferentemente con cursos de formación docente."),
        new("CSOF", "38002", "VERIFICACION Y VALIDACION DE SOFTWARE  ", 4, 2, 10, 2, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, con experiencia docente a nivel superior, con experiencia profesional en el área de desarrollo de software de al menos un año, preferentemente con cursos de formación docente."),
        new("DSOF", "38001", "PRINCIPIOS DE CONSTRUCCION DE SOFTWARE  ", 4, 2, 10, 2, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, con experiencia docente a nivel superior, con experiencia profesional en el área de desarrollo de software de al menos un año, preferentemente con cursos de formación docente."),
        new("DSOF", "38002", "TECNOLOGIAS PARA LA CONSTRUCCION DE SOFTWARE  ", 4, 2, 10, 2, " Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, con experiencia docente a nivel superior, con experiencia profesional en el área de desarrollo de software de al menos un año, preferentemente con cursos de formación docente."),
        new("DSOF", "38003", "DESARROLLO DE SOFTWARE  ", 3, 2, 8, 2, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, con experiencia docente a nivel superior, con experiencia profesional en el área de desarrollo de software de al menos un año, preferentemente con cursos de formación docente."),
        new("DSOF", "38004", "DESARROLLO DE APLICACIONES  ", 2, 4, 8, 2, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, con experiencia docente a nivel superior, con experiencia profesional en el área de desarrollo de software de al menos un año, preferentemente con cursos de formación docente."),
        new("DSOF", "38005", "DESARROLLO DE SISTEMAS WEB  ", 3, 3, 9, 2, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, con experiencia docente a nivel superior, con experiencia profesional en el área de desarrollo de software de al menos un año, preferentemente con cursos de formación docente."),
        new("DSOF", "38006", "DESARROLLO DE SISTEMAS EN RED  ", 4, 2, 10, 2, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, con experiencia docente a nivel superior, con experiencia profesional en el área de desarrollo de software de al menos un año, preferentemente con cursos de formación docente."),
        new("DSOF", "38007", "PRACTICAS DE INGENIERIA DE SOFTWARE  ", 3, 3, 9, 2, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, con experiencia docente a nivel superior, con experiencia profesional en el área de desarrollo de software de al menos un año, preferentemente con cursos de formación docente."),
        new("ENSO", "38001", "DERECHO DE LAS TECNOLOGIAS DE INFORMACION Y COMUNICACION  ", 3, 2, 8, 2, "Lic. en Derecho con Maestría en Derecho Informático o afín, con experiencia profesional, con experiencia docente en el nivel superior y preferentemente con cursos de formación docente"),
        new("ENSO", "38002", "ECONOMIA PARA TOMA DE DECISIONES  ", 2, 2, 6, 2, "Licenciatura en Contaduría, Administración de Empresas, Economía, con Maestría o Doctorado en el área de administración, con experiencia docente en el nivel superior y en el desarrollo de proyectos de inversión; preferentemente con cursos de formación docente."),
        new("EXRE", "38002", "PROYECTO GUIADO  ", 2, 3, 7, 2, "Licenciado en Ingeniería de Software, en Informática o afín con posgrado en Ingeniería de Software o en el área de la Computación, con cursos de formación docente y experiencia docente a nivel superior, experiencia profesional en el área de desarrollo de software de al menos dos años y con experiencia en investigación."),
        new("MASF", "38001", "REQUERIMIENTOS DE SOFTWARE  ", 4, 2, 10, 2, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, con experiencia docente a nivel superior, preferentemente con cursos de formación docente y con experiencia profesional en el área de desarrollo de software de al menos un año."),
        new("MASF", "38002", "PRINCIPIOS DE DISEÑO DE SOFTWARE  ", 4, 2, 10, 2, " Licenciado en Ingeniería de Software, en Informática o afín con posgrado en Ingeniería de Software o en el área de la Computación, con experiencia docente a nivel superior, preferentemente con cursos de formación docente y experiencia profesional en el área de desarrollo de software de al menos un año."),
        new("MASF", "38003", "DISEÑO DE SOFTWARE  ", 4, 2, 10, 2, "Licenciado en Ingeniería de Software, en Informática o afín con posgrado en Ingeniería de Software o en el área de la Computación, con experiencia docente a nivel superior preferentemente con cursos de formación docente y con experiencia profesional en el área de desarrollo de software de al menos un año."),
        new("PRGM", "38003", "ESTRUCTURAS DE DATOS  ", 3, 3, 9, 2, "Licenciado en Informática o carrera afín, con posgrado en el área de la computación, con experiencia en programación orientada a objetos y/o certificación en lenguajes de programación orientada a objetos, experiencia docente a nivel superior en el área de programación y cursos de formación docente."),
        new("PRGM", "38004", "PARADIGMAS DE PROGRAMACION  ", 4, 2, 10, 2, "Lic. en Informática o carrera afín, con posgrado en el área de la computación, con experiencia en programación y/o certificación en lenguajes de programación, experiencia docente a nivel superior en el área de programación y cursos de formación docente."),
        new("RDCO", "38001", "REDES  ", 3, 3, 9, 2, "Licenciatura en Informática o afín, con estudios de posgrado en el área de redes y/o tecnología educativa, con experiencia docente de al menos 2 años en nivel superior."),
        new("SICC", "38001", "BASES DE DATOS  ", 3, 3, 9, 2, "Licenciado  en  Informática  o  carrera  afín  con  posgrado  en  el  área  de  la  computación  y preferentemente con certificación en Bases de Datos, con experiencia docente en el nivel superior de  al  menos  2  años  y  con  experiencia  profesional  académica  en  el  área  de  Bases  de  Datos Centralizadas, y con cursos de formación docente."),
        new("ARSI", "38007", "SISTEMAS OPERATIVOS MOVILES  ", 2, 2, 6, 3, "Licenciado en Informática o carrera afín con grado de maestría en el área, con experiencia mínima  docente de dos años en en nivel superior."),
        new("ERIS", "38004", "EXPERIENCIA RECEPCIONAL  ", 0, 4, 12, 3, "Licenciado en Ingeniería de Software, en Informática o afín con posgrado en Ingeniería de Software o en el área de la Computación, con cursos de formación docente y experiencia docente a nivel superior, experiencia profesional en el área de desarrollo de software de al menos dos años y con experiencia en investigación."),
        new("EXAV", "00001", "ACREDITACION DEL IDIOMA INGLES  ", 0, 0, 6, 3, null),
        new("ISOP", "38001", "BASES DE DATOS NO CONVENCIONALES  ", 2, 2, 6, 3, "Licenciado en informática o carrera similar, con experiencia demostrable en el desarrollo de software y/o manejo de bases de datos, con posgrado en el área de Ciencias de la Computación, con experiencia docente a nivel superior y con cursos de formación docente."),
        new("ISOT", "38002", "INTELIGENCIA ARTIFICIAL APLICADA A LA INGENIERIA DE SOFTWARE  ", 2, 2, 6, 3, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, con experiencia docente a nivel superior, preferentemente con cursos de formación docente, y con experiencia profesional en el área de desarrollo de software de al menos un año."),
        new("ISOT", "38003", "MEDICION DE SOFTWARE  ", 2, 2, 6, 3, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, con experiencia docente a nivel superior, con experiencia profesional en el área de desarrollo de software de al menos un año, preferentemente con cursos de formación docente."),
        new("ISOT", "38004", "PROGRAMACION MULTINUCLEO  ", 2, 2, 6, 3, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, con experiencia docente a nivel superior, con experiencia profesional en el área de desarrollo de software de al menos un año, preferentemente con cursos de formación docente."),
        new("ISOT", "38005", "PROYECTOS DE SOFTWARE  ", 2, 2, 6, 3, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software  o  en  el  área  de  la  Computación,  con  experiencia  docente  a  nivel  superior,  con experiencia  profesional   en  el   área  de  desarrollo  de   software  de  al   menos  un  año, preferentemente con cursos de formación docente.\n"),
        new("ISOT", "38006", "REINGENIERIA DE SOFTWARE  ", 2, 2, 6, 3, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, preferentemente con cursos de formación docente y experiencia docente a nivel superior, con experiencia profesional en el área de desarrollo de software de al menos un año."),
        new("ISOT", "38007", "DISEÑO DE INTERFACES DE USUARIO  ", 2, 2, 6, 3, "Licenciado en Ingeniería de Software, en Informática o afín, con posgrado en Ingeniería de Software o en el área de la Computación, preferentemente con cursos de formación docente, con experiencia docente a nivel superior, con experiencia profesional en el área de desarrollo de software de al menos un año."),
        new("ISOT", "38008", "ADMINISTRACION AVANZADA DE SERVICIOS  ", 2, 3, 7, 3, "Licenciado en Informática o carrera afín, con experiencia profesional demostrable y comprobable en administración de servidores, preferentemente con maestría en el área de redes o afín o certificaciones en el área. Al menos un año de experiencia docente en educación superior."),
        new("ISOT", "38009", "PROGRAMACION SEGURA  ", 3, 2, 8, 3, "Licenciado en Informática o carrera afin con grado de maestría, con experiencia comprobable en el desarrollo de sistemas y administración de servicios de red, así como en el desarrollo de software de red. Con experiencia docente en nivel superior."),
        new("ISOT", "38010", "SISTEMAS OPERATIVOS MOVILES  ", 2, 2, 6, 3, "Licenciado en Informática o carrera afín con grado de maestría en el área, con experiencia mínima  docente de dos años en en nivel superior."),
        new("ISOT", "38011", "PRUEBAS DE PENETRACION  ", 2, 2, 6, 3, "Licenciatura en Informática o afín, con estudios de posgrado en el área de redes, seguridad de cómputo o certificaciones en el área, con experiencia docente de al menos 2 años en nivel superior y experiencia profesional en el área de seguridad de cómputo."),
        new("ISOT", "38012", "ADMINISTRACION DE BASES DE DATOS  ", 2, 2, 6, 3, "Licenciado  en  Informática  o  carrera  afín  con   posgrado   en   el   área   de   la   computación, con experiencia en bases de datos relacionales y/o con certificación en Bases de Datos, con experiencia docente en el nivel superior de al menos 2 años en bases de datos y con cursos de formación docente."),
        new("RSCO", "38004", "PRUEBAS DE PENETRACION  ", 2, 2, 6, 3, "Licenciatura en Informática o afín, con estudios de posgrado en el área de redes o seguridad de cómputo o certificaciones en el área de seguridad en cómputo, con experiencia docente de al menos un año en nivel superior y experiencia profesional en el área de seguridad de cómputo."),
        new("SICC", "38004", "ADMINISTRACION DE BASES DE DATOS  ", 2, 2, 6, 3, "Licenciado  en  Informática  o  carrera  afín  con   posgrado   en   el   área   de   la   computación, con experiencia en bases de datos relacionales y/o con certificación en Bases de Datos, con experiencia docente en el nivel superior de al menos 2 años en bases de datos y con cursos de formación docente."),
        new("SSSO", "38003", "SERVICIO SOCIAL  ", 0, 4, 12, 3, "Licenciado en Informática ó carrera afín, preferentemente con posgrado en el área de Computación, con experiencia en vinculación y experiencia docente en el nivel superior."),
    ];
}

/// <summary>Una experiencia educativa del cuerpo de la importación; sin cupos, que el Excel no trae.</summary>
internal sealed record ExperienciaDeEjemplo(
    string Materia,
    string Curso,
    string Nombre,
    int HorasTeoricas,
    int HorasPracticas,
    int Creditos,
    int AreaFormacionId,
    string? PerfilDocente)
{
    public int? CupoMinimo { get; init; }

    public int? CupoMaximo { get; init; }
}
